name: "Check Sphinx docs build"
on: 
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
  docs:
    runs-on: ubuntu-latest
    - uses: actions/checkout@v1
    - uses: ammaraskar/sphinx-action@master
      with:
        docs-folder: "docs/"
